services:
- type: web
  name: typesense
  env: docker
  repo: https://github.com/SmebdyNbdy/typesense-on-render.git
  plan: starter
  healthCheckPath: /health
  envVars:
  - key: TYPESENSE_API_KEY
    generateValue: true
  - key: TYPESENSE_DATA_DIR
    value: /typesense-data
  - key: TYPESENSE_ENABLE_CORS
    value: true
